import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const notoSans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Festivente - WMS",
  // description: "Generated by create next app",
};

const SITEMAP = [
    {
        name: "Dashboard",
        icon: "dashboard",
        path: "/"
    },
    {
        name: "Magazyn",
        icon: "dashboard",
        path: "/magazyn"
    },
    {
        name: "Wypożyczenia",
        icon: "dashboard",
        path: "/wypozyczenia"
    },
    {
        name: "Pracownicy",
        icon: "dashboard",
        path: "/pracownicy"
    },
    {
        name: "Imprezy",
        icon: "dashboard",
        path: "/imprezy"
    },
    {
        name: "Transport",
        icon: "dashboard",
        path: "/transport"
    },
    {
        name: "Serwis",
        icon: "dashboard",
        path: "/serwis"
    },
]

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={notoSans.className}>
        <nav>
            <div className="logo">LOGO</div>
            <ul className="menu">
                {SITEMAP.map((item) => (
                    <li key={item.path}>
                        <Link href={item.path}>
                            {item.name}
                        </Link>
                    </li>
                ))}
            </ul>
        </nav>
        <div>
            <header></header>
            <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
