import type {Metadata} from "next";
import {Noto_Sans} from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import UIIcon from '@/components/UI/Icon'
import * as Icons from "iconsax-react";

const notoSans = Noto_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Festivente - WMS",
    // description: "Generated by create next app",
};

interface SitemapItem {
    name: string;
    icon: keyof typeof Icons;
    path: string;

}

const SITEMAP = [
    {
        name: "Dashboard",
        icon: "Category",
        path: "/dashboard"
    },
    {
        name: "Magazyn",
        icon: "Box",
        path: "/warehouse"
    },
    {
        name: "Wypożyczenia",
        icon: "Convert3DCube",
        path: "/rentals"
    },
    {
        name: "Pracownicy",
        icon: "Profile2User",
        path: "/employees"
    },
    {
        name: "Imprezy",
        icon: "Star",
        path: "/events"
    },
    {
        name: "Transport",
        icon: "Truck",
        path: "/transport"
    },
    {
        name: "Serwis",
        icon: "Setting",
        path: "/service"
    },
] as Array<SitemapItem>;

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
        <body className={notoSans.className}>
        <nav>
            <div className="logo">LOGO</div>
            <ul className="menu">
                {SITEMAP.map((item) => (
                    <li key={item.path}>
                        <Link href={item.path}>
                            <UIIcon name={item.icon} size={24}/>
                            <span>{item.name}</span>
                        </Link>
                    </li>
                ))}
            </ul>
        </nav>
        <div>
            <header></header>
            <main>{children}</main>
        </div>
        </body>
        </html>
    );
}
