import {ReactNode} from "react";
import type {Metadata} from "next";
import {Noto_Sans} from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import {SITEMAP} from "@/sitemap";
// import UIIcon from '@/components/UI/Icon'

const notoSans = Noto_Sans({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Festivente - WMS",
    // description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="pl">
        <body className={notoSans.className}>
        <nav>
            <div className="logo">LOGO</div>
            <ul className="menu">
                {SITEMAP.map((item) => (
                    <li key={item.path}>
                        <Link href={item.path}>
                            {/*<UIIcon name={item.icon} size={24}/>*/}
                            <span>{item.name}</span>
                        </Link>
                    </li>
                ))}
            </ul>
        </nav>
        <div>
            <header></header>
            <main>{children}</main>
        </div>
        </body>
        </html>
    );
}
